title: Ali Gilbert # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Lifelong learner and mathematics famatic  <br><br>
  <a href="https://www.linkedin.com/in/ali-gilbert/">View My LinkedIn Profile</a> 
   <a href="https://public.tableau.com/app/profile/aligilbert/">View My Tableau Public Account</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
